services:

  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    pull_policy: always
    container_name: openwebui
    network_mode: service:tailscale-ingress
    # ports:
    #   - "8080:8080"
    environment:
      - WEBUI_PORT=8080
      - OLLAMA_BASE_URL=http://localhost:11434
      - WEBUI_SECRET_KEY=
    volumes:
      - /data/openwebui:/app/backend/data
    restart: unless-stopped
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    pull_policy: always
    network_mode: service:tailscale-ingress
    # ports:
    #   - "11434:11434"
    volumes:
      - /data/ollama:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  # prometheus:
  #   image: bitnami/prometheus:2
  #   container_name: prometheus
  #   restart: unless-stopped
  #   volumes:
  #     - ./prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
  #     - /data/prometheus:/opt/bitnami/prometheus/data
  #   # ports:
  #   #   - 9091:9090

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    pull_policy: always
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  dcgm-exporter:
    image: nvidia/dcgm-exporter:4.2.3-4.1.3-ubuntu22.04
    container_name: dcgm-exporter
    network_mode: host
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    # ports:
    #   - "9400:9400"
    cap_add:
      - SYS_ADMIN
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  tailscale-ingress:
    image: tailscale/tailscale:latest
    pull_policy: always
    hostname: ai-snow
    env_file:
      - .env
    environment:
      # - TS_AUTHKEY= # from .env file
      - TS_SERVE_CONFIG=/config/ts-config.json
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /data/tailscale-ingress:/var/lib/tailscale
      - ./ts-config.json:/config/ts-config.json
    extra_hosts:
      - host.docker.internal:host-gateway
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: always