services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    pull_policy: always
    container_name: openwebui
    # ports:
    #   - "8080:8080"
    environment:
      - WEBUI_PORT=8080
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=
    volumes:
      - /data/openwebui:/app/backend/data
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    pull_policy: always
    # ports:
    #   - "11434:11434"
    volumes:
      - /data/ollama:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  swag:
    image: linuxserver/swag:latest
    container_name: swag
    pull_policy: always
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=snow-ai.duckdns.org
      # - SUBDOMAINS=wildcard
      # - ONLY_SUBDOMAINS=false
      - VALIDATION=duckdns
      # - DUCKDNSTOKEN=from .env file
    volumes:
      - /data/swag:/config
      - ./openwebui.subdomain.conf:/config/nginx/site-confs/default.conf:ro
    ports:
      - "443:443"
      # - "80:80"
    restart: unless-stopped