# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s 


scrape_configs:
  
  - job_name: "node"
    static_configs:
    - targets: 
      - host.docker.internal:9100 # node exporter

  - job_name: "nvidia"
    scrape_interval: 10s
    static_configs:
      - targets: 
        - host.docker.internal:9400

  - job_name: "openwebui"
    scrape_interval: 10s
    static_configs:
      - targets: 
        - https://ai-snow.reindeer-pinecone.ts.net