---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgC49Vx+yF/yQcrdli0PBfAVPEqmkyjQjPVC+K5byugCVWx2Yku5OBWh1W+DpO2bcKfHw4nijCgt67qNfjLPn8IGdzCyRzH8+5gyRHHGV6jPjtTQJtbl2TqKSFDO8Ewdl3iQSFnWG/nj+QD8LITw9MVDBa/RVTgqc5Sz1e0twZL+zoqB604SD57NziigLdYpMh9Bhj6ngmBZZ6dX9jIP+OMJtngqPiYixkeO4WOz0NxbnsHlRFBAvyWq2aCiDHmYVfAnQwdvR5ec1PLtj9BSpbh6OZucIjJOUhd8NqVp4txAmuh0a+C6LMllptGupsIGozjQSNH8iqitA4VUpR4Sq6VPIi9J6BagaqLXHMNl2xVKXHKJJpvXACP+snzEWzT3deeKusAu4PD5lX49qacugfyKfNglfrdky1iugID/3FPhLIzUXIqiqQWobpyekWuW1es56P5Ii3EGQT33rbIqfQwXj9pT9ba/wuaDugOhv//y71yI0VvcaQ+HAdUOp0Gd5zfBppn6XFmi+rbqxPK0/CeyQMaZsiGeFPq1kdgurcbMt9HcT9EN531M0B2ec4ax4y4dR+zFKWpsuqpRz/oPcA1FC+8mAFSwszbMuca+hMpvqliQJDWo//CDKaGSqiQaTyZ7tsTd0ItFRACA3nScVD0aRq3hVVFWPGwC8vV2nBhGbLTSzPZrROmeoAD8mpogVdGwnTsgUZP8gNwFnxFrxnBYaZqO9UHfSVdVPumklwY3MDH8sVTMYEjo6wQMuFOsZjv/Vqr9jhOfez6HGJNhU1NTyb7zdlntpRx8cnWrWqjnEpQmOPeioZBXqX/i3shYRogvdRBEaP2dB6CMZZEjy9FREIpjwfD6tYEZ6NX1qP6oPhjDHBnxDLZUBn78Y2H2fBfcBPpfmesxwcuLbzMCz2SMTfptK3dnjxDFHg2Udgron9Mhp0k=
  template:
    metadata:
      name: cloudflared-credentials
      namespace: cloudflared
