- name: setup users playbook
  hosts: all
  become: yes
  vars_files:
    - secrets.yml

  tasks:
    - name: setup usernames, passwords, and groups
      user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        groups: docker,sudo
        append: yes
      no_log: true
      loop: "{{ users }}"