apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: cloudflare-tags
  namespace: istio-system
spec:
  metrics:
  - providers:
    - name: prometheus
    overrides:
    - tagOverrides:
        cf_ray:
          value: request.headers["cf-ray"]
        cf_country:
          value: request.headers["cf-ipcountry"]