apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
        version: v1
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2026.6.0
          args:
            - tunnel
            - --no-autoupdate
            - --metrics
            - 0.0.0.0:20241
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
            - 141192d6-c05c-4cb4-816b-56bd6ce29b1b
          livenessProbe:
            httpGet:
              path: /ready
              port: 20241
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 1
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
            - name: credentials
              mountPath: /etc/cloudflared/credentials.json
              subPath: credentials.json
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: cloudflared-config
        - name: credentials
          secret:
            secretName: cloudflared-credentials
