apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: 141192d6-c05c-4cb4-816b-56bd6ce29b1b
    credentials-file: /etc/cloudflared/credentials.json

    protocol: http2

    ingress:
      - hostname: "alexsimplesyllabuscheck.snowse.io"
        service: http://istio-ingressgateway.istio-system.svc.cluster.local:80
        
      - hostname: "*.snowse.io"
        service: http://main-gateway-istio.istio-system.svc.cluster.local:80

        originRequest:
          http2Origin: false
          disableChunkedEncoding: true
          connectTimeout: 30s

      - service: http_status:404