apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snow-se-tools-secret # external secret name
  namespace: snow-se-tools
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: snow-se-tools-secret # secret that will be created
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        property: POSTGRES_PASSWORD
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: snow-se-tools
        nullBytePolicy: Ignore
    - secretKey: DATABASE_URL
      remoteRef:
        property: DATABASE_URL
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: snow-se-tools
        nullBytePolicy: Ignore
    - secretKey: OIDC_ISSUER
      remoteRef:
        property: OIDC_ISSUER
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: snow-se-tools
        nullBytePolicy: Ignore
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        property: OIDC_CLIENT_ID
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: snow-se-tools
        nullBytePolicy: Ignore
    - secretKey: AI_ENDPOINT
      remoteRef:
        property: AI_ENDPOINT
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: snow-se-tools
        nullBytePolicy: Ignore
    - secretKey: AI_API_KEY
      remoteRef:
        property: AI_API_KEY
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: snow-se-tools
        nullBytePolicy: Ignore
    - secretKey: SECRET_KEY_BASE
      remoteRef:
        property: SECRET_KEY_BASE
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: snow-se-tools
        nullBytePolicy: Ignore
