services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: 1000:1000
    command:
      - '--enable-feature=promql-experimental-functions'
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - /home/alex/data/prometheus:/prometheus
      
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: 1000:1000
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      -  /home/alex/data/grafana:/var/lib/grafana

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /data/heimdall:/config
    ports:
      - 3080:80
    restart: unless-stopped
volumes:
  prom_data:
  grafana-storage: