apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# ── Source ────────────────────────────────────────────────────────────────────
resources:
  - ../../base

configMapGenerator:
  - name: app-config
    namespace: pantheon
    behavior: merge
    literals:
      - PHX_HOST=alexpantheon.snowse.io
      - OIDC_REDIRECT_URI=https://alexpantheon.snowse.io/auth/callback
      - POOL_SIZE=10
      - PORT=4000

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: pantheon
        namespace: pantheon
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: pantheon
        template:
          metadata:
            labels:
              app: pantheon
          spec:
            containers:
              - name: pantheon
                image: ghcr.io/alexmickelson/pantheon-gateway:24
  - patch: |-
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: pantheon
        namespace: pantheon
      spec:
        parentRefs:
          - group: gateway.networking.k8s.io	
            kind: Gateway	
            name: main-gateway
            namespace: istio-system
        hostnames:
          - "alexpantheon.snowse.io"
