apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# ── Source ────────────────────────────────────────────────────────────────────
bases:
  - ../../base

images:
  - name: ghcr.io/alexmickelson/pantheon-gateway
    newName: ghcr.io/alexmickelson/ai-pantheon
    newTag: "2"

configMapGenerator:
  - name: app-config
    namespace: pantheon
    behavior: merge
    literals:
      - PHX_HOST=alexpantheon.snowse.io
      - POOL_SIZE=10
      - PORT=4000

patches:
  - patch: |-
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: pantheon
        namespace: pantheon
      spec:
        parentRefs:
          - name: main-gateway
            namespace: istio-system
        hostnames:
          - "alexpantheon.snowse.io"
