; https://huggingface.co/blog/ggml-org/model-management-in-llamacpp
; https://github.com/ggml-org/llama.cpp/pull/17859

[Qwen3.5-122B-A10B-Q4_K_M]
model = /models/Qwen3.5-122B-A10B-Q4_K_M-00001-of-00003.gguf
mmproj = /models/mmproj-Qwen3.5-122B.gguf
jinja = on
threads = -1
ctx-size = 100000
temp = 0.6
top-k = 20
min-p = 0.00
top-p = 0.95

[qwen3.5-27b]
model = /models/Qwen3.5-27B-UD-Q8_K_XL.gguf
mmproj = /models/Qwen3.5-27B-GGUF-mmproj-F32.gguf
jinja = on
ctx-size = 0


[qwen3.6-35b]
model = /models/Qwen3.6-35B-A3B-UD-Q8_K_XL.gguf
mmproj = /models/Qwen3.6-35B-GGUF-mmproj-F32.gguf
jinja = on
ctx-size = 0
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.00


[qwen3.6-27b]
model = /models/Qwen3.6-27B-BF16-00001-of-00002.gguf
mmproj = /models/qwen3.6-27b-mmproj-F32.gguf
jinja = on
ctx-size = 0
temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 1.5
min-p = 0.00