apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-web-ts-dep
  namespace: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-web-ts
  template:
    metadata:
      labels:
        app: keycloak-web-ts
    spec:
      containers:
        - name: keycloak-web-ts
          image: quay.io/keycloak/keycloak:26.0.0
          command:
            - /opt/keycloak/bin/kc.sh
            - start-dev
          ports:
            - containerPort: 8080
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_USERNAME
              value: keycloak
            - name: KC_DB_PASSWORD
              value: thisisthelongpaesrabasdfasdfseerbserbsfbssowrd
            - name: KC_DB_URL
              value: jdbc:postgresql://keycloak-db-ts-service:5432/keycloak
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: admin
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: admin
            - name: KC_HOSTNAME
              value: https://auth.snowse-ts.duckdns.org
            - name: KC_PROXY_HEADERS
              value: xforwarded
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080