- name: setup users playbook
  hosts: all
  become: true

  vars_files:
    - ../secrets.yml

  tasks:
    - name: setup usernames, passwords, and groups
      user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        groups: docker,sudo
        append: yes
        shell: /usr/bin/bash # try to only run first time in case students want to change their shell
      no_log: true
      loop: "{{ users }}"

    - name: remove other users
      user:
        name: "{{ item.name }}"
        state: absent
        remove: yes
      loop: "{{ users_to_remove }}"

    - name: setup alex user
      user:
        name: alex
        groups: docker,sudo
        append: yes
      no_log: true