global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: node_exporter
  honor_timestamps: true
  scrape_interval: 5s
  static_configs:
  - targets:
    - alex-office1.tail8bfa2.ts.net:9100
    - alex-office2.tail8bfa2.ts.net:9100
    - alex-office3.tail8bfa2.ts.net:9100
    - alex-office4.tail8bfa2.ts.net:9100
    - alex-office5.tail8bfa2.ts.net:9100
- job_name: docker
  static_configs:
    - targets: 
      - alex-office1.tail8bfa2.ts.net:9323
      - alex-office2.tail8bfa2.ts.net:9323
      - alex-office3.tail8bfa2.ts.net:9323
      - alex-office4.tail8bfa2.ts.net:9323
      - alex-office5.tail8bfa2.ts.net:9323
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
    - targets: 
      - alex-office1.tail8bfa2.ts.net:9091
      - alex-office2.tail8bfa2.ts.net:9091
      - alex-office3.tail8bfa2.ts.net:9091
      - alex-office4.tail8bfa2.ts.net:9091
      - alex-office5.tail8bfa2.ts.net:9091