apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: 42b1bab8-3465-4aa3-a418-5b976383c606
    credentials-file: /etc/cloudflared/credentials.json

    ingress:
      - hostname: alexargocd.snowse.io
        service: http://main-gateway-istio.istio-system.svc.cluster.local:80
      - hostname: alexmonitoring.snowse.io
        service: http://main-gateway-istio.istio-system.svc.cluster.local:80
      - hostname: alexopencost.snowse.io
        service: http://main-gateway-istio.istio-system.svc.cluster.local:80
      - service: http_status:404
