---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgABTNln0oqEhVDKDcuh0pFdL0x0j19/IrofoulEb7kArPSJkteSYDvU7DSUvk+7sr9cRJGy/Mqb8m3Rc9J1Re0jmWzkuwLYTwIldQYw9uwlMVFFcZ+xRLMoCkivObWY9kq0H8LQjBzjrDc1WaVmXMfSYbVdHXD1/pdWobnUhvfuyupPVCIaQ3KKKkboQJXJ6YitAnjzo4yhTUjzuEwDRfYFyMXwdcqj8SpMrxuAmRU38D8hoTglJyRP6JACp+IB7/a3XaQkovDwQEhwWDuIa5FUFH9ZC0tjuOX+eDgQIVFVyeotWy66wVHlrheTmyEJ99V8kol4LZQvbVRriMGJa+iKEWEhYLx7o8kACxQ8FnNVdQWrxyjKFlrLGXWaGZedH3TYS/lIPdUcLAgZozszqfjZPXJevKVHRnWOG+IFhU/o/evXBs57vGoGo+hmxTjzvLu19TET2APJTIRJWcwoD4XINouDOkzdRVdtfxo0jVDS+BohRndTmfPhBlFzfAwRa2Dxd1AjVs+ahEfwt+Pr5VUGebd/5TXvwOk0nB4UKBy/0E7OwWV/DtcsZDMTR1cuRd1PUQRJpz3azJePiHMYqxkpyR7aa0vmt/Jh2VtQOphIl6cDgVX1pBK11azcSHVR1jSPTc6SnAUNK2OmigzqmL6mYDTEm144rrXCRhrbD8ZhDcLYy0VomRpmKWXzGTJSk/avZ/+wNEYO8dbyA6w5fc9zsozwKU5brnShZpdsSyEnfChtaa4LjCVX+lbdvb6cmDGmgKo9Uu0CyxtQyiR4fXDH/7KYvV/t6pyQfKoYLopbU9MaxNyJYP/9cq8dAjW5/mU7ZP13V/uS7NhRPHK2cED650c8PnyUwGDaFXqhWX34qXA3ZkstxQhfi0GvwUKL2LM6z5d3+FnY/sFEUdwVFw3apbnrRz6xNm2UvQMhMHiTkqtf
  template:
    metadata:
      name: cloudflared-credentials
      namespace: cloudflared
