---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgCo3yF9kp6iD3pt+A+QQT1k7Wx9UxAvX32hEOaJ1EQZHt0NmJSoErm26DfiObaFoMpMMvmfoOyVn0cgWn8fjpPOmGz8QRQFyBuqzel+kfdizrW9uZyTDRdu37Le64YqlqFyCZbHiQX6LzsnNSV2RvpcT5YDTYl4dhw+P/gKVth92BUl4q+xla1lXlcYnGXHckJTyo1QioW9N9SgYD+PZsbhaueApRSZ1XLtA8h3E8gjKkyIuDPpVnYQYuMxfXupAfoFRy3vBfPmlv/wTiDvMHd4O5tXpv0jF+xxSn1/dbpyPcnatJHct8U4A7e74Ql7OSSzt+xzgG6jHvGNin9/pqpRfGgDLzL0FqLYSCWCivdbwNiiEQ4t/1ihYP5sWYNO4EW2leK+V5ZS8pqTxv2Vt8vaXLQppKgFSixIhJSOwJIAWIPNBsVEFcrAo//+/uRullv6OQnTx+aBE7wuSY3DOAd+0eoelTusSvZ2ylCsDVAz1SBscx77VK3nJ4QunoNP6uQqcYrjavtAGiWFx302wDSP+9MIKZI2Frafly24UNMzNujv6Lh1HKyshiUVlyIPfm6n5qGAQ2V5Dr8baXzlWtMTDlV8+Q8UAfCGKSRMJ7hNbkwNWf6nYQKSF2/Ed8WWCEJpkBSjH/iI5+OT5RigJT/CCHYfbZIsTTV9+wX8e0qCClolNC2h6H+CWvgVihvGNVG0QRucu9XCZtfhUkOV0mmxM75cD3Vd7/EqZ2hzfePzz9rygS+r7RLbATyYgMwSnoLXLMuGL7oUbO19jJBlYOp9jj6V23GIwUdUBPFHrN9ysd0+kvO4kaiUQVB6ILHOmjFt4AHITEbfmKgWX0rDmPjfJGE9RMDRHzB0cMG8SZ9PlIR/hEjf9Khl+Qr0OJ4aysKoftO4pDMvEoEpOFZcsDp3xyz0rzfVaTtYbewUJX7sXisfo4U=
  template:
    metadata:
      name: cloudflared-credentials
      namespace: cloudflared
