apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discordadminbot-secrets
  namespace: discord-bot
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: discordadminbot-secrets
    creationPolicy: Owner
  data:
    - secretKey: DISCORD_BOT_TOKEN
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: discord-bot/config
        property: DISCORD_BOT_TOKEN
        nullBytePolicy: Ignore
    - secretKey: DISCORD_GUILD_ID
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: discord-bot/config
        property: DISCORD_GUILD_ID
        nullBytePolicy: Ignore
