apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./externalsecret.yml
  - https://raw.githubusercontent.com/SnowSE/discordAdminBot/main/kube/deployment.yaml
  - https://raw.githubusercontent.com/SnowSE/discordAdminBot/main/kube/service.yaml
  - https://raw.githubusercontent.com/SnowSE/discordAdminBot/main/kube/pvc.yaml
  - https://raw.githubusercontent.com/SnowSE/discordAdminBot/main/kube/httproute.yaml

namespace: discord-bot

patchesJson6902:
  - target:
      kind: Deployment
      name: discordadminbot
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/snowse/discordadminbot:5
  - target:
      kind: HTTPRoute
      name: discordadminbot
    patch: |
      - op: replace
        path: /spec/parentRefs/0
        value:
          group: gateway.networking.k8s.io
          kind: Gateway
          name: main-gateway
          namespace: istio-system
      - op: replace
        path: /spec/hostnames
        value:
          - "discordadmin.snowse.io"
      - op: add
        path: /spec/rules/0/backendRefs/0/group
        value: ""
      - op: add
        path: /spec/rules/0/backendRefs/0/kind
        value: Service
      - op: add
        path: /spec/rules/0/backendRefs/0/weight
        value: 1
