apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  # 1
  - openSSH:
      address: 144.17.92.11
      user: root
    role: controller+worker
    noTaints: true
    privateInterface: eno1
    # installFlags:
    # - --kubelet-extra-args="--node-ip=144.17.92.11"
  # 2
  - openSSH:
      address: 144.17.92.12
      user: root
    role: controller+worker
    noTaints: true
    privateInterface: eno1
    # installFlags:
    # - --kubelet-extra-args="--node-ip=144.17.92.12"
  # 3
  - openSSH:
      address: 144.17.92.13
      user: root
    role: controller+worker
    noTaints: true
    privateInterface: eno1
    # installFlags:
    # - --kubelet-extra-args="--node-ip=144.17.92.13"
  # 4
  - openSSH:
      address: 144.17.92.14
      user: root
    role: controller+worker
    noTaints: true
    privateInterface: eno1
    # installFlags:
    # - --kubelet-extra-args="--node-ip=144.17.92.14"
  # 5
  - openSSH:
      address: 144.17.92.15
      user: root
    role: controller+worker
    noTaints: true
    privateInterface: eno1
    # installFlags:
    # - --kubelet-extra-args="--node-ip=144.17.92.15"
  k0s:
    config:
      spec:
        telemetry:
          enabled: true
    version: v1.31.1+k0s.1
