apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  # 1
  - openSSH:
      address: 144.17.92.11
      user: root
    role: controller+worker
    noTaints: true
    privateInterface: eno1
    # installFlags:
    # - --kubelet-extra-args="--node-ip=144.17.92.11"
  # 2
  - openSSH:
      address: 144.17.92.12
      user: root
    role: controller+worker
    noTaints: true
    privateInterface: eno1
    # installFlags:
    # - --kubelet-extra-args="--node-ip=144.17.92.12"
  # 3
  - openSSH:
      address: 144.17.92.13
      user: root
    role: controller+worker
    noTaints: true
    privateInterface: eno1
    # installFlags:
    # - --kubelet-extra-args="--node-ip=144.17.92.13"
  # 5
  - openSSH:
      address: 144.17.92.15
      user: root
    role: controller+worker
    noTaints: true
    privateInterface: eno1
    # installFlags:
    # - --kubelet-extra-args="--node-ip=144.17.92.15"
  k0s:
    version: v1.29.3+k0s.0
    # dynamicConfig: false
    # config: 
    #   apiVersion: k0s.k0sproject.io/v1beta1
    #   kind: ClusterConfig
    #   metadata:
    #     name: class-cluster
      # spec:
        # api:
        #   address: 144.17.92.12
