apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: alex
  name: nfs-test
spec:
  accessModes:
    - ReadWriteMany
  # storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi