apiVersion: v1
kind: Namespace
metadata:
  name: discord-bot
  labels:
    istio-injection: enabled
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: discord-bot
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: discord-bot-policy
  namespace: discord-bot
spec:
  selector:
    matchLabels:
      app: discordadminbot
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces: ["istio-system"]
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discord-bot
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/alexmickelson/office-infrastructure.git
    targetRevision: main
    path: ai-office-server/kubernetes/argocd/discord-bot

    kustomize:
      commonAnnotations:
        argocd.argoproj.io/managed-by: argocd

  destination:
    server: https://kubernetes.default.svc
    namespace: discord-bot

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
