apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    istio-injection: enabled
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: external-dns
spec:
  mtls:
    mode: STRICT
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: "1.21.1"
    helm:
      releaseName: external-dns
      values: |
        provider:
          name: cloudflare
        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: external-dns-cloudflare
                key: cloudflare-api-token
        sources:
          - gateway-httproute
        domainFilters:
          - snowse.io
        policy: sync
        txtOwnerId: office-k3s
        extraArgs:
          cloudflare-proxied: true
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
