apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
  labels:
    istio-injection: enabled
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: tailscale
spec:
  mtls:
    mode: STRICT
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://pkgs.tailscale.com/helmcharts
    chart: tailscale-operator
    targetRevision: "*"
    helm:
      releaseName: tailscale-operator
      values: |
        oauth:
          existingSecret: operator-oauth
        proxyConfig:
          defaultProxyClass: no-istio-k8s-api
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: no-istio-k8s-api
spec:
  statefulSet:
    pod:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "443"
