apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    chart: jaeger
    targetRevision: "4.7.0"
    helm:
      releaseName: jaeger
      values: |
        query:
          basePath: "/jaeger"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jaeger
  namespace: argocd
spec:
  parentRefs:
    - name: main-gateway
      namespace: istio-system
  hostnames:
    - "alexmonitoring.snowse.io"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /jaeger
      backendRefs:
        - name: jaeger
          namespace: monitoring
          port: 16686
---
# Istio sends traces to zipkin.istio-system:9411 by default.
# This ExternalName service routes that traffic to Jaeger in the monitoring namespace.
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: istio-system
spec:
  type: ExternalName
  externalName: jaeger.monitoring.svc.cluster.local
  ports:
    - port: 9411
      targetPort: 9411
      name: http-query
