; https://huggingface.co/blog/ggml-org/model-management-in-llamacpp
; https://github.com/ggml-org/llama.cpp/pull/17859

; [gpt-oss-120b]
; model = /models/gpt-oss-120b-F16.gguf
; jinja = on
; ngl = 99
; flash-attn = on
; ctx-size = 16384
; batch-size = 2048
; ubatch-size = 2048
; temp = 1.0
; top-p = 1.0
; top-k = 0


; [gemma3-27b]
; model = /models/gemma-3-27b-it-Q2_K_L.gguf
; mmproj = /models/gemma-mmproj-F16.gguf
; jinja = on
; ngl = 99
; flash-attn = on
; ctx-size = 0


; [gemma4-31b]
; model = /models/gemma-4-31B-it-BF16-00001-of-00002.gguf
; mmproj = /models/mmproj-gemma4-BF16.gguf
; jinja = on
; ngl = 99
; flash-attn = on
; ctx-size = 0
; temp = 1.0
; top-k = 64
; top-p = 0.95


[qwen3.5-122b]
model = /models/Qwen3.5-122B-A10B-Q4_K_M-00001-of-00003.gguf
mmproj = /models/mmproj-Qwen3.5-122B.gguf
jinja = on
ngl = 99
flash-attn = on
ctx-size = 100000
threads = -1
temp = 0.6
top-k = 20
min-p = 0.00
top-p = 0.95


[qwen3.6-27b]
model = /models/Qwen3.6-27B-Q6_K.gguf
mmproj = /models/qwen3.6-27b-mmproj-F16.gguf
jinja = on
ctx-size = 262144
temp = 1.0
top-k = 20
min-p = 0.0
top-p = 0.95
presence-penalty = 1.5

; [granite-4.0-h-small]
; model = /models/granite-4.0-h-small-Q4_K_M.gguf
; jinja = on
; ngl = 99
; flash-attn = on
; ctx-size = 0

