apiVersion: v1
kind: Namespace
metadata:
  name: hermes
  annotations:
    repo: "https://github.com/alexmickelson/office-infrastructure"
    path: "ai-office-server/kubernetes/hermes/rbac/01-namespace.yml"
  labels:
    app: hermes
    name: hermes
