services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    env_file:
      - .env
    ports:
      - "4000:4000" # Map the container port to the host, change the host port if necessary
    environment:
      - DATABASE_URL=postgres://siteuser:postgresewvraer@localhost/my_db
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
      - STORE_MODEL_IN_DB='True'
    volumes:
      - ./litellm-config.yaml:/app/config.yaml # Mount the local configuration file
    command: [ "--config", "/app/config.yaml", "--port", "4000", "--num_workers", "8" ]

  litellm_db:
    container_name: litellm_db
    image: postgres:17
    environment:
      - POSTGRES_USER=siteuser
      - POSTGRES_PASSWORD=postgresewvraer
      - POSTGRES_DB=my_db
    volumes:
        - /data/litellm_db:/var/lib/postgresql/data


  # cloudflare-tunnel:
  #   image: cloudflare/cloudflared
  #   container_name: cloudflare-tunnel
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   command: tunnel run
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #   environment:
  #     - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
  #   healthcheck:
  #     test: [ "CMD", "cloudflared", "--version" ]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 10s