services:
  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    env_file:
      - .env
    ports:
      - 127.0.0.1:4000:4000
    environment:
      - DATABASE_URL=postgres://siteuser:postgresewvraer@localhost/my_db
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
      - STORE_MODEL_IN_DB='True'
    volumes:
      - ./litellm-config.yaml:/app/config.yaml
    args: ["--config", "/app/config.yaml"]
    healthcheck:
      test: [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 http://localhost:4000/health/liveliness || exit 1",
        ] # Command to execute for health check
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  litellm_db:
    container_name: litellm_db
    image: postgres:17
    environment:
      - POSTGRES_USER=siteuser
      - POSTGRES_PASSWORD=postgresewvraer
      - POSTGRES_DB=my_db
    volumes:
      - /data/litellm_db:/var/lib/postgresql/data

  # cloudflare-tunnel:
  #   image: cloudflare/cloudflared
  #   container_name: cloudflare-tunnel
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   command: tunnel run
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #   environment:
  #     - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
  #   healthcheck:
  #     test: [ "CMD", "cloudflared", "--version" ]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 10s
