# not using currently because config stored in DB rn
# general_settings:
#     user_header_name: X-OpenWebUI-User-Email
#     store_model_in_db: True
model_list:
  - model_name: gpt-oss-120b
    litellm_params:
      model: openai/gpt-oss-120b # Added openai/ prefix for OpenAI-compatible endpoint
      api_base: http://host.docker.internal:9292
      api_key: "none" # Required for OpenAI-compatible endpoints, use "none" if no key needed
