# not using currently because config stored in DB rn
# general_settings:
#     user_header_name: X-OpenWebUI-User-Email
#     store_model_in_db: True
model_list:
  - model_name: gpt-oss-120b
    litellm_params:
      model: openai/gpt-oss-120b
      api_base: http://host.docker.internal:9292/v1
      api_key: "none"
      input_cost_per_token:  0.00000015
      output_cost_per_token: 0.00000060
  - model_name: gemma3-27b
    litellm_params:
      model: openai/gemma3-27b
      api_base: http://host.docker.internal:9292/v1
      api_key: "none"
      input_cost_per_token:  0.00000008
      output_cost_per_token: 0.00000060