opencost:
  prometheus:
    internal:
      enabled: false
    external:
      enabled: true
      url: http://prometheus-server.prometheus-system.svc.cluster.local:80
  metrics:
    kubeStateMetrics:
      emitKsmV1Metrics: false
      emitKsmV1MetricsOnly: false
